# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Greetings

on: 
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting for issues
      if: github.event_name == 'issues'
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Thank you @${{ github.event.issue.user.login }} for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!

    - name: Send greeting for pull requests
      if: github.event_name == 'pull_request'
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          🎉 Thank you @${{ github.event.pull_request.user.login }} for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better.
